<a href="https://colab.research.google.com/github/shanmukhaReddyK/AI_Search/blob/main/A_star_grid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

map = np.zeros((4,4), dtype=int)

map[1,1]=1
map[2,1]=1
map[2,2]=1

start = (0,0)
end = (3,3)



print("Map with obstacles")
print(map)
print(f"Start: {start}")
print(f"End: {end}")

Map with obstacles
[[0 0 0 0]
 [0 1 0 0]
 [0 1 1 0]
 [0 0 0 0]]
Start: (0, 0)
End: (3, 3)
0
0
3


In [ ]:
import heapq

def manhattan_distance(point1,point2):
  #calculate manhattan distance between tow points
  return abs(point1[0]-point2[0])+abs(point1[1]-point2[1])

def astar(grid,start,goal):
  rows, cols = grid.shape
  open_set =[]

  heapq.heappush(open_set,(0,start)) #(f_cost, node)

  came_from = {}
  g_cost = {}
  f_cost = {}

  g_cost[start] = 0
  f_cost[start] = manhattan_distance(start, end)

  while open_set:
    current_f_cost, current_node = heapq.heappop(open_set)

    if current_node == goal:
      path = []
      while current_node in came_from:
        path.append(current_node)
        current_node = came_from[current_node]
      path.append(start)
      path.reverse()
      return path

    #if the node is not the goal then we explore neighbors (horizontal and vertical moves)
    for dr, dc in [(0,1),(0,-1),(1,0),(-1,0)]:
        neighbor_row, neighbor_col = current_node[0]+dr, current_node[1]+dc
        neighbor_node = (neighbor_row,neighbor_col)

        if(0 <= neighbor_row < rows and 0 <= neighbor_col < cols and grid[neighbor_row, neighbor_col]==0):
            tentative_g_cost = g_cost[current_node]+1
            if neighbor_node not in g_cost or tentative_g_cost < g_cost[neighbor_node]:
                g_cost[neighbor_node] = tentative_g_cost
                f_cost[neighbor_node] = tentative_g_cost + manhattan_distance(neighbor_node,end)
                heapq.heappush(open_set,(f_cost[neighbor_node], neighbor_node))
                came_from[neighbor_node] = current_node
  return None

path = astar(map,start,end)

if path:
    print("shortest path found:")
    print(path)
else:
    print("No path found")


shortest path found:
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 3), (2, 3), (3, 3)]
